name: CI

on:
  push:
    branches:
      - master
      - release/**
    tags:
      - v*.*.*
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup display
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        if: contains(matrix.os, 'ubuntu')

      - name: Install, build, and test
        run: |
          npm ci
          npm run compile
          npm test
          npm run package
        env:
          CI: true
          DISPLAY: ":99.0"

  publish:
    if: startsWith(github.ref, 'refs/tags/')

    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Publish
        run: |
          npm ci
          npm run package
          npm run deploy -p ${{ secrets.VSCE_TOKEN }}

      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          files: ./clang-tidy-*.*.*.vsix
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
